apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: classic-besu 
  namespace: ethercluster
  labels:
    app: classic-besu
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: classic-besu
  serviceName: classic-besu
  template:
    metadata:
      name: classic-besu
      labels:
        app: classic-besu
    spec:
      containers:
        - name: besu
          image: "hyperledger/besu:latest"
          imagePullPolicy: Always
          args: 
          - "--network=classic"
          - "--data-path=/classic-besu-data"
          #- "--db-path=/classic-besu-data/chains" 
          #- "--keys-path=/classic-besu-data/keys"
          - "--rpc-http-enabled" 
          - "--rpc-ws-enabled"
          ports:
            - containerPort: 8545
              protocol: TCP
              name: rpc-port
            - containerPort: 8546
              protocol: TCP
              name: ws-port
            - containerPort: 443
              protocol: TCP
              name: https
          readinessProbe:
            httpGet:
              port: 8545
              path: /api/health
            initialDelaySeconds: 9000 
            periodSeconds: 1800
          livenessProbe:
            tcpSocket:
              port: 8545
              path: /api/health
            initialDelaySeconds: 9000
            periodSeconds: 1800
          volumeMounts:
            - name: classic-besu-data
              mountPath: /classic-besu-data
        - name: ethnetintel
          image: etccoop/ethnetintel
          env:
          - name: NAME_PREFIX
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: WS_SERVER
            value: classic-besu-stats.dcp
          - name: WS_SECRET
            valueFrom:
              secretKeyRef:
                name: classic-besu-stats
                key: WS_SECRET
          - name: RPC_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: RPC_PORT
            value: "8545"
    volumes:
      - name: classic-besu-data
  volumeClaimTemplates:
    - metadata:
        name: classic-besu-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "classic-besu-ssd"
        resources:
          requests:
            storage: 50Gi
