apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: classic 
  namespace: ethercluster
  labels:
    app: classic
spec:
  replicas: 4 
  selector:
    matchLabels:
      app: classic
  serviceName: classic
  template:
    metadata:
      name: classic
      labels:
        app: classic
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: parity
          image: "parity/parity:v2.5.3-beta"
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
          command: ["/parity/parity"]
          args: 
          - "--chain=classic"
          - "--base-path=/classic-data"
          - "--db-path=/classic-data/chains" 
          - "--keys-path=/classic-data/keys"
          - "--jsonrpc-port=8545"
          - "--jsonrpc-interface=0.0.0.0"
          - "--jsonrpc-apis=web3,eth,net,rpc,parity"
          - "--jsonrpc-cors=all"
          - "--jsonrpc-hosts=all"
          - "--no-ancient-blocks"
          - "--no-serve-light"
          - "--max-peers=250"
          - "--snapshot-peers=50"
          - "--ws-interface=0.0.0.0"
          - "--ws-apis=web3,eth,net,rpc,parity"
          - "--ws-origins=all"
          - "--ws-hosts=all"
          ports:
            - containerPort: 8545
              protocol: TCP
              name: rpc-port
            - containerPort: 8546
              protocol: TCP
              name: ws-port
            - containerPort: 443
              protocol: TCP
              name: https
          readinessProbe:
            httpGet:
              port: 8545
              path: /api/health
            initialDelaySeconds: 9000 
            periodSeconds: 1800
          livenessProbe:
            tcpSocket:
              port: 8545
              path: /api/health
            initialDelaySeconds: 9000
            periodSeconds: 1800
          volumeMounts:
            - name: classic-data
              mountPath: /classic-data
        - name: ethnetintel
          image: etccoop/ethnetintel
          env:
          - name: NAME_PREFIX
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: WS_SERVER
            value: classic-stats.dcp
          - name: WS_SECRET
            valueFrom:
              secretKeyRef:
                name: classic-stats
                key: WS_SECRET
          - name: RPC_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: RPC_PORT
            value: "8545"
    volumes:
      - name: classic-data
  volumeClaimTemplates:
    - metadata:
        name: classic-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "classic-ssd"
        resources:
          requests:
            storage: 50Gi
